---
- name: Install backend dependencies
  apt:
    name: "{{ backend_dependencies }}"
    state: present

- name: Create /etc/backend directory
  ansible.builtin.file:
    path: /etc/backend
    state: directory

- name: Copy backend configuration file
  template:
    src: backend.config.j2
    dest: /etc/backend/backend.config