- name: Install Softwares
  hosts: all
  become: true
  vars:
    packages:
      - name: nginx
        required: True
      - name: apache
        required: False
  tasks:
  - name: Install "{{ item.name }}" on Debian
    apt:
      name: "{{ item.name }}"
      state: present
    when: item.required == True
    loop: "{{ packages }}"

