---
- name: Install frontend dependencies
  apt:
    name: "{{ frontend_dependencies }}"
    state: present

- name: Copy frontend configuration file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html